version: '3.7'
services:
  db:
    platform: linux/amd64
    image: mysql:8.1 # or postgres:xx
    container_name: my-nextjs-starter-db-dev
    restart: always
    ports: # defaults are postgres=5432, mysql=3306
      - "5433:5432"
      - "3307:3306"
    env_file:
      - .env.development
    volumes:
      - db:/var/lib/postgresql/data
      - db:/var/lib/mysql
  db-test:
    platform: linux/amd64
    image: mysql:8.1
    container_name: my-nextjs-starter-db-test
    restart: always
    ports:
      - "5434:5432"
      - "3308:3306"
    env_file:
      - .env.test
    volumes:
      - db-test:/var/lib/postgresql/data
      - db:/var/lib/mysql
volumes:
  db:
    name: my-nextjs-starter-db
  db-test:
    name: my-nextjs-starter-db-test