name: Frontend Lint

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: "Run eslint / tsc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: eslint
        run: pnpm lint
      - name: tsc
        run: pnpm type-check
